# << installation dependant directories === MacOSX ============================
TCLA    := /usr/lib/libtcl.dylib
TKA     := /usr/lib/libtk.dylib
X11A    := /usr/X11/lib/libX11.dylib

TCLH    := /usr/include
TKH     := /usr/include
X11H    := /usr/X11/include

MLD     := /usr/local/lib/ocaml
MLA     := $(MLD)/libcamlrun.a
ILibs   := -I $(SE_HOME)/src -I $(SE_HOME)/builtin

LL      := -lm -lunix -lthreads

CMA     := unix.cma
CMX     := unix.cmxa

SERC    := .serc_unix

TARGET  := unix
