// generated : Please do not edit this file  
// -------------------------------------------- 
Identity2_path=get_absolute_file_path('loader.sce');
link(Identity2_path+'libIdentity2.so',['se_Identity2'],'c');
scicos ;
